workflows:
  ios-workflow:
    name: iOS Future You Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc, development, enterprise
        bundle_identifier: com.futureyou.os
      
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Flutter analyze
        script: |
          flutter analyze
      
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_CONNECT_ISSUER_ID" "$APP_STORE_CONNECT_KEY_IDENTIFIER" "$APP_STORE_CONNECT_PRIVATE_KEY" "$BUNDLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # CHANGE THIS to your email
        notify:
          success: true
          failure: true
      
      # Uncomment when ready to publish to App Store
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Beta Testers
  
  # Android workflow (if you need it later)
  android-workflow:
    name: Android Future You Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build APK
        script: |
          flutter build apk --release
      
      - name: Build AAB
        script: |
          flutter build appbundle --release
    
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # CHANGE THIS
        notify:
          success: true
          failure: true

